### ISSUE TITLE
Elasticsearch ERROR

### ISSUE THREAD

**Issue by jiangwei1995** [sat-utils/sat-api-express#4]
POST http://localhost:9200/sat-api/_search?size=1&from=0 => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/Users/jiangwei/work/searchTile/sat-api-express/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/jiangwei/work/searchTile/sat-api-express/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/Users/jiangwei/work/searchTile/sat-api-express/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/Users/jiangwei/work/searchTile/sat-api-express/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1277:8)

Elasticsearch WARNING: 2017-10-13T04:53:05Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-10-13T04:53:05Z
  No living connections

2017-10-13T04:53:05.031Z - error:  Error: No Living connections
    at sendReqWithConnection (/Users/jiangwei/work/searchTile/sat-api-express/node_modules/elasticsearch/src/lib/transport.js:207:15)
    at next (/Users/jiangwei/work/searchTile/sat-api-express/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by drewbo** [comment]
Hi @jiangwei1995, can you give more information about the error you're encountering (e.g. what did you try that led to this)? From a quick look, it doesn't appear that the elasticsearch server is running locally
